# Classical Sentiment Classification Baselines

This notebook repeats the best performing classical NLP experiments from the legacy notebook on the cleaned project splits.

Models:
1. Bag-of-Words + Logistic Regression
2. TF-IDF + Naive Bayes
3. TF-IDF + Logistic Regression
4. TF-IDF + Linear SVC

## Choice of Classical Baselines

The classical experiments focus on linear models trained on Bag-of-Words and TF-IDF representations. This is a natural starting point for sentiment analysis because these representations produce high-dimensional and sparse feature vectors, where linear models often perform very well.

Logistic Regression is used as the main classical baseline because it is simple, fast, robust, and well suited for sparse text features. It also provides a strong comparison point before moving to transformer-based models.

Naive Bayes is included as a traditional probabilistic baseline for text classification. Although it relies on stronger independence assumptions, it is efficient and often competitive on sentiment classification tasks.

Linear SVC is included as another strong linear classifier for sparse TF-IDF features.

More complex tree-based models, such as Random Forests or Gradient Boosting methods, are not included at this stage. These models are usually less effective on sparse, high-dimensional TF-IDF features and can add computational complexity without providing a clear advantage. For this reason, the classical baseline section focuses on methods that are both standard and well matched to the feature representation.

## Imports

In [1]:
import re
from pathlib import Path

import pandas as pd
import spacy
from bs4 import BeautifulSoup

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.pipeline import Pipeline

## Load the processed dataset

In [2]:
DATA_DIR = Path("../data/processed")

train_df = pd.read_csv(DATA_DIR / "train.csv")
valid_df = pd.read_csv(DATA_DIR / "valid.csv")
test_df = pd.read_csv(DATA_DIR / "test.csv")

train_df.head()

                                                text  label
0  I was seriously looking forward to seeing this...      0
1  `Mad Dog' Earle is back, along with his sad-sa...      1
2  * Firstly, although many say it is the worst o...      1
3  I love science fiction, I am fascinated by Egy...      0
4  One measurement for the greatness of a movie i...      1

In [3]:
print("Train:", train_df.shape)
print("Validation:", valid_df.shape)
print("Test:", test_df.shape)

print("\nTrain label distribution:")
print(train_df["label"].value_counts().sort_index())

print("\nValidation label distribution:")
print(valid_df["label"].value_counts().sort_index())

print("\nTest label distribution:")
print(test_df["label"].value_counts().sort_index())

Train: (8000, 2)
Validation: (2000, 2)
Test: (2000, 2)

Train label distribution:
label
0    4000
1    4000
Name: count, dtype: int64

Validation label distribution:
label
0    1000
1    1000
Name: count, dtype: int64

Test label distribution:
label
0    1000
1    1000
Name: count, dtype: int64

## Preprocessing

The preprocessing follows the legacy notebook closely:
- remove HTML tags
- lowercase text
- tokenize with spaCy
- remove punctuation and spaces
- remove stopwords, but keep negations
- lemmatize tokens

In [4]:
nlp = spacy.load("en_core_web_sm")

negations = {
    "not", "no", "n't", "isn't", "aren't", "won't",
    "can't", "never", "nothing"
}


def preprocess_review(review: str) -> str:
    # Remove HTML tags
    review = BeautifulSoup(review, "html.parser").get_text(" ")

    # Remove social-style mentions/hashtags if present
    review = re.sub(r"(@[A-Za-z0-9_]+)|(#\S+)", " ", review)

    doc = nlp(review.lower())

    clean_tokens = []
    for token in doc:
        if token.is_punct or token.is_space:
            continue
        if token.is_stop and token.text not in negations:
            continue

        clean_tokens.append(token.lemma_)

    return " ".join(clean_tokens)

In [5]:
# Quick preprocessing check
example = train_df.loc[0, "text"]

print("Original review:")
print(example[:500])

print("\nProcessed review:")
print(preprocess_review(example)[:500])

Original review:
I was seriously looking forward to seeing this film because it seemed truly promising from the coming attractions: Jim Carrey with Godlike powers was an idea that most definitely worked for me. As a huge fan, I was sure he'd be supremely in his element with such a promising premise, and what could go wrong? Yesterday, my bubble got burst big-time, boys and girls, because I saw the movie.   The first act (where it's set up that he hates his life, he's a disgruntled employee and a majorly unhappy

Processed review:
seriously look forward see film truly promising come attraction jim carrey godlike power idea definitely work huge fan sure supremely element promising premise wrong yesterday bubble get burst big time boy girl see movie act set hat life disgruntled employee majorly unhappy camper ax grind god serviceable second act summon god telephone receive power almighty great carrey get fun new toy pleasure watch funny act wretche belief rot start set dinner scene bruce girlfriend grace jennifer aniston co

In [6]:
# Preprocess all splits
train_df["processed_text"] = train_df["text"].apply(preprocess_review)
valid_df["processed_text"] = valid_df["text"].apply(preprocess_review)
test_df["processed_text"] = test_df["text"].apply(preprocess_review)

train_df[["text", "processed_text", "label"]].head()

,text,processed_text,label
0,I was seriously looking forward to seeing this...,seriously look forward see film truly promisin...,0
1,"`Mad Dog' Earle is back, along with his sad-sa...",` mad dog earle sad sack moll marie fickle clu...,1
2,"* Firstly, although many say it is the worst o...",firstly bad series not think true consider ide...,1
3,"I love science fiction, I am fascinated by Egy...",love science fiction fascinate egyptian mythol...,0
4,One measurement for the greatness of a movie i...,measurement greatness movie come t.v right wan...,1

## Evaluation helper

In [7]:
target_names = ["negative", "positive"]


def evaluate_model(model_name, model, X_train, y_train, X_valid, y_valid):
    model.fit(X_train, y_train)

    y_pred = model.predict(X_valid)

    accuracy = accuracy_score(y_valid, y_pred)

    print(f"{model_name}")
    print("=" * len(model_name))
    print(f"Accuracy: {accuracy:.4f}")
    print("\nClassification report:")
    print(classification_report(y_valid, y_pred, target_names=target_names))

    return {
        "model_name": model_name,
        "model": model,
        "accuracy": accuracy,
        "predictions": y_pred,
    }

In [8]:
X_train = train_df["processed_text"]
y_train = train_df["label"]

X_valid = valid_df["processed_text"]
y_valid = valid_df["label"]

X_test = test_df["processed_text"]
y_test = test_df["label"]

## 1. Bag-of-Words + Logistic Regression

In [9]:
bow_lr_pipeline = Pipeline([
    ("vectorizer", CountVectorizer(max_features=5000, ngram_range=(1, 2))),
    ("classifier", LogisticRegression(max_iter=1000, class_weight="balanced")),
])

bow_lr_results = evaluate_model(
    "Bag-of-Words + Logistic Regression",
    bow_lr_pipeline,
    X_train,
    y_train,
    X_valid,
    y_valid,
)

Bag-of-Words + Logistic Regression
==================================
Accuracy: 0.8445

Classification report:
              precision    recall  f1-score   support

    negative       0.85      0.84      0.84      1000
    positive       0.84      0.85      0.85      1000

    accuracy                           0.84      2000
   macro avg       0.84      0.84      0.84      2000
weighted avg       0.84      0.84      0.84      2000

## 2. TF-IDF + Naive Bayes

In [10]:
tfidf_nb_pipeline = Pipeline([
    ("vectorizer", TfidfVectorizer(max_features=5000, ngram_range=(1, 2))),
    ("classifier", MultinomialNB()),
])

tfidf_nb_results = evaluate_model(
    "TF-IDF + Naive Bayes",
    tfidf_nb_pipeline,
    X_train,
    y_train,
    X_valid,
    y_valid,
)

TF-IDF + Naive Bayes
====================
Accuracy: 0.8515

Classification report:
              precision    recall  f1-score   support

    negative       0.87      0.83      0.85      1000
    positive       0.84      0.88      0.85      1000

    accuracy                           0.85      2000
   macro avg       0.85      0.85      0.85      2000
weighted avg       0.85      0.85      0.85      2000

## 3. TF-IDF + Logistic Regression

In [11]:
tfidf_lr_pipeline = Pipeline([
    ("vectorizer", TfidfVectorizer(max_features=5000, ngram_range=(1, 2))),
    ("classifier", LogisticRegression(max_iter=1000, class_weight="balanced")),
])

tfidf_lr_results = evaluate_model(
    "TF-IDF + Logistic Regression",
    tfidf_lr_pipeline,
    X_train,
    y_train,
    X_valid,
    y_valid,
)

TF-IDF + Logistic Regression
============================
Accuracy: 0.8670

Classification report:
              precision    recall  f1-score   support

    negative       0.89      0.84      0.86      1000
    positive       0.85      0.90      0.87      1000

    accuracy                           0.87      2000
   macro avg       0.87      0.87      0.87      2000
weighted avg       0.87      0.87      0.87      2000

In [26]:
from sklearn.svm import LinearSVC

tfidf_svm_model = Pipeline([
    ("vectorizer", TfidfVectorizer(max_features=5000, ngram_range=(1, 2))),
    ("classifier", LinearSVC(C=1.0)),
])

tfidf_svm_model.fit(train_df["processed_text"], train_df["label"])

tfidf_svm_predictions = tfidf_svm_model.predict(valid_df["processed_text"])

tfidf_svm_accuracy = accuracy_score(valid_df["label"], tfidf_svm_predictions)

print("Accuracy:", tfidf_svm_accuracy)
print("\nClassification Report:\n")
print(classification_report(
    valid_df["label"],
    tfidf_svm_predictions,
    target_names=["negative", "positive"]
))

tfidf_svm_results = {
    "model_name": "TF-IDF + Linear SVC",
    "model": tfidf_svm_model,
    "accuracy": tfidf_svm_accuracy,
    "predictions": tfidf_svm_predictions,
}

Accuracy: 0.858

Classification Report:

              precision    recall  f1-score   support

    negative       0.87      0.84      0.86      1000
    positive       0.85      0.87      0.86      1000

    accuracy                           0.86      2000
   macro avg       0.86      0.86      0.86      2000
weighted avg       0.86      0.86      0.86      2000

## Compare validation results

In [21]:
results = [
    bow_lr_results,
    tfidf_nb_results,
    tfidf_lr_results,
    tfidf_svm_results,
]

comparison_df = pd.DataFrame([
    {
        "model": result["model_name"],
        "validation_accuracy": round(result["accuracy"], 4),
    }
    for result in results
])

comparison_df.sort_values("validation_accuracy", ascending=False)

                                model  validation_accuracy
2        TF-IDF + Logistic Regression               0.8670
3                 TF-IDF + Linear SVC               0.8580
1                TF-IDF + Naive Bayes               0.8515
0  Bag-of-Words + Logistic Regression               0.8445

## Error examples

In [22]:
# Inspect misclassified validation examples

label_map = {
    0: "negative",
    1: "positive",
}

valid_errors = valid_df.copy()
valid_errors["predicted_label"] = tfidf_lr_results["predictions"]
valid_errors["true_sentiment"] = valid_errors["label"].map(label_map)
valid_errors["predicted_sentiment"] = valid_errors["predicted_label"].map(label_map)

misclassified = valid_errors[
    valid_errors["label"] != valid_errors["predicted_label"]
].copy()

print(f"Number of misclassified examples: {len(misclassified)}")
print(f"Validation set size: {len(valid_errors)}")
print(f"Error rate: {len(misclassified) / len(valid_errors):.3f}")

Number of misclassified examples: 266
Validation set size: 2000
Error rate: 0.133

In [23]:
# Display a few misclassified examples clearly

pd.set_option("display.max_colwidth", 500)

examples_to_show = misclassified[
    ["true_sentiment", "predicted_sentiment", "text"]
].sample(10, random_state=42)

for i, row in examples_to_show.reset_index(drop=True).iterrows():
    print("=" * 100)
    print(f"Example {i + 1}")
    print(f"True label:      {row['true_sentiment']}")
    print(f"Predicted label: {row['predicted_sentiment']}")
    print("-" * 100)
    print(row["text"][:1500])
    print()

====================================================================================================
Example 1
True label:      negative
Predicted label: positive
----------------------------------------------------------------------------------------------------
The plot of 'House of Games' is the strongest thing about it: a successful author and psychologist is conned by a gang of grifters, but in discovering the wicked part of herself that enjoys the thrill of what they do, she finally gets her revenge. That's about the pitch: but someone has to take responsibility for it coming across as being acted by puppets. It has to be the director Mamet: Lindsay Crouse has had a varied and pretty steady TV and film career, so she can't perform this badly all the time. She's supposed to go from uptight, cool, controlled professional to calculating, wicked fast lady having fun, as shown by the change from beige trouser suit (which she seems to wear for three days straight, including underwear) to floppy floral sundress. But everyone seems to be speaking their lines the same clipped, precise way; I imagine Mamet wanting to make sure not a syllable of his scintillating script got missed. The effect is unsettling and spoils the atmosphere of mystery and suspense he is presumably trying to create. At times 'House of Games' loses any connection to how human beings actually behave or talk, and becomes just a mechanism to spin out the plot. The clunky vibes'n'oboe faux-jazz soundtrack doesn't help either. The ultimate result is that the only entertainment to be had is in guessing the outcome, and the sooner you do that the sooner you will get bored with the robotic, two-dimensional performances. And they smoke too much!!!

====================================================================================================
Example 2
True label:      negative
Predicted label: positive
----------------------------------------------------------------------------------------------------
What starts out as a gentle country yarn, inoffensive and mildly enjoyable romantic tale changes pace as Edward Norton's initially charming Harlan gradually reveals more about himself and things take a turn for the sinister, as the film gradually changes from a southern romance to a modern wild western.  An amiable rancher (Norton) wanders into town and charms a young girl (Evan Rachel Wood), seemingly rescuing her from a dead-end existence with her bad-tempered father with a whirlwind romance, but it gradually becomes apparent that there is more to this cowboy than meets the eye.  Edward Norton  a real chameleon actor (with changing facial hair to match) playing a country hick, accent slightly dodgy but maybe because he's merely trying to act the part without worrying about the accent. He certainly makes it appear effortless to make all the nuanced little adjustments as we learn more about Harlan. However, with too many small changes it means we are never sure exactly where Harlan is coming from, and what seemed like a good performance from Norton gradually becomes confused. Evan Rachel Wood is likable without ever really having a great deal to do other than bat her eyelids at Norton.  Down in the Valley strikes as a slightly uneven tale due to its change of pace, and by never really making the protagonist's motives clear the audience's sympathies for the characters remain uncertain. Should we like this drifter or not? Even after a dramatic turn of events it remains unclear

====================================================================================================
Example 3
True label:      negative
Predicted label: positive
----------------------------------------------------------------------------------------------------
In the Tower of Babel installment of the mini-series, the narrator describes the builders of the tower as "the descendants of Moses."  That's like saying George Washington lived many centuries before Alexander the Great.  Or that the light bulb was invented before the wheel.  Or that the guided missile was the forerunner of the bow-and-arrow.  Need I say more?  The writers of The Greatest Heroes of the Bible should have at least paid closer attention to the chronologies of Biblical people and events.

====================================================================================================
Example 4
True label:      positive
Predicted label: negative
----------------------------------------------------------------------------------------------------
I have seen my fair share of comedy and standup movies but this one is so original, so fresh, it will make you wonder why you always walked right pass it in the video store. Murphy has some pretty raunchy jokes but this is just too funny to pass. If only every movie could be this funny. it should be called "107 minutes of the most incredible comedy" Murphy is a comic genius in this film and will make you say "this is the guy that did dr. doulittle!" He talkes about the ice cream man, shoe throwing mothers, his aunt with a mustache, racism, and everything else you could possibly think of and the ones you couldnt. Please if you ever see one comedy in your life this is it, if only all movies could be Delirious.

====================================================================================================
Example 5
True label:      negative
Predicted label: positive
----------------------------------------------------------------------------------------------------
this movie, i won't call it a "film," was basically about nothing and functioned mostly for the popular acts of the time. yeah the war was on full swing (pun intended), and this movie gave the troops and our audiences a treat.  but let's have something with a bit more substance.  loved seeing a young Buddy Rich on the drums. the music was good throughout.  but one cameo after another gets old fast.  i didn't even recognize Zero Mostel! so if you're one from the "greatest generation," as they say, you'll definitely enjoy this...  movie.

====================================================================================================
Example 6
True label:      positive
Predicted label: negative
----------------------------------------------------------------------------------------------------
this movie is another on the list that i did not want to see. i was talked into it and dragged into the theater, but boy am i glad for that. i thought it was going to be just another love story, but it turns out to be SOOO much more than that. definatly an intellectual flick, one of those movies you have to pay attention to.

====================================================================================================
Example 7
True label:      negative
Predicted label: positive
----------------------------------------------------------------------------------------------------
Andie McDowell is beautiful as the 40-ish woman whose late start at a serious relationship leads her to a considerably younger man and a subsequenet falling-out with 2 long-time best girldfriends.  Seeing a gigolo/gold-digger in the sincere young man, the "girl-friends", dead-set on terminating this "silly relationship", go over and beyond the call of duty in "helping out" their friend (who obviously is blinded by this gigolo's tricky game".  A short succession of situations is absolutely ridiculous. Far fetched no longer covers it. Without these unbelievable scenes, there may have been hope for a sweet love story. Instead, all the viewer is left with is an involuntary shaking of head -- these things just don't happen! Without giving away cliff-hanger details, I warn the viewer of having high expectations for this film; most (like me) will be very disappointed. On a scale of 1 to 10, this one ranks a weak 4 with me. There is much better material out there. This one isn't worth your time.

====================================================================================================
Example 8
True label:      positive
Predicted label: negative
----------------------------------------------------------------------------------------------------
The quintessential road movie...if your idea of a road movie involves three would-be magicians with Eastern European accents and Claire Forlani. (Well, one out of four ain't bad...) A no-talent magician with an eye for showmanship (Max) watches a very skilled pickpocket (Hugo) plying his trade in New York. After convincing Hugo that he (Max) is a) mental and b) desperately in need of a partner to make his dreams of being a stage magician come alive, the not-so-dynamic duo enlist the managerial expertise of an inventor of illusions (Milo) and the, ah, gentler attributes of a lovely waitress (Lydia). The unlikely four pile into a van (obtained by Hugo...you guess where it came from) and head to Vegas. Havoc ensues. Anyhow, it's funny, it's well-written, and the ending is surprisingly good. A solid comedy with a warm heart, and all the better that it was totally unexpected.

====================================================================================================
Example 9
True label:      negative
Predicted label: positive
----------------------------------------------------------------------------------------------------
A broke would be screenwriter and his would be agent (Tom Wood and Arye Gross) are forced to live in a self storage facility run by an eccentric and intimidating manager (Ron Perlman) whom they come to believe is the serial murderer that is terrorizing the city, the "Costume Killer" (so named because, after injecting his victims with Windex, he dresses them in silly costumes). They convince him his life story would make a great film and gather together a group of misfit wannabe film makers (John Considine, Joe Pantoliano, Kristy Swanson) and discover that the art of movie making can be murder.  There is more to this movie but it was unfortunately left on the editing room floor and it shows (rumor is the studio wanted a "lighter" dark comedy). Our loss (and the actors, who all do fine jobs and deserve better) as this has the makings of an exceptional black comedy but only rises to mediocre cute.  If you're a Ron Perlman fan this is absolutely worth getting just for his performance. His comedic timing is excellent and he has the chance to do some really great impressions (he wasn't kidding when he said on the Hellboy movie commentary that he needed an intervention when he gets into Jerry Lewis mode). He's just simply fun to watch in this one.   David Dukes also shines in a two-scener (but pivotal) role.

====================================================================================================
Example 10
True label:      negative
Predicted label: positive
----------------------------------------------------------------------------------------------------
Too Much of Something Borrowed Grade B-  Super Bowl Sunday is one of the slowest days at movie theaters every year. Because of this, movie studios tend to avoid releasing bigger budgeted films that weekend. Every few years a studio releases a counter-programming female skewing movie (2001's "The Wedding Planner") to compete with the big game. This Super Bowl weekend similarly titled "The Wedding Date" will try to find success and attract viewers not watching the game.   Sick of people feeling sorry for her, single-woman, Kat Ellis (Debra Messing, TV's "Will and Grace") hires male escort Nick ( Dermot Mulrony, "About Schmidt") to pose as her boyfriend for her sister's wedding in London. Her family has been giving her a hard time about her not being married, and her ex- fiancé of seven years, who dumped her without a reason, is the best man. To make him jealous Kat parades Nick around her ex to make him see what he is missing. But ultimately Nick helps Kat realize that she can open up, and let someone love her.  The film borrows too much from similar wedding movies. It is almost a carbon copy of 1999's "Picture Perfect" and mixes in scenes similar to "The Wedding Planner" and "My Best Friends Wedding". The movie also has a reverse "Pretty Women" theme going for it, and knowing her audience, the director makes clever references to that and other films.  "The Wedding Date" has all the clichéd elements of a typical wedding movie, there is the stereotypical overbearing mother (Holl

The misclassified examples often contain mixed sentiment, contrastive phrasing, or a delayed final judgment. Negative reviews may include positive descriptions of specific aspects before ending with an overall negative evaluation, while positive reviews may begin with negative expectations before reversing them. This suggests that simple BoW/TF-IDF models are limited by their weak treatment of context and discourse structure.

## Evaluate the best model on the test set

In [ ]:
best_result = max(results, key=lambda result: result["accuracy"])
best_model = best_result["model"]
best_model_name = best_result["model_name"]

test_pred = best_model.predict(X_test)

print(f"Best validation model: {best_model_name}")
print(f"Test accuracy: {accuracy_score(y_test, test_pred):.4f}")

print("\nTest classification report:")
print(classification_report(y_test, test_pred, target_names=target_names))

Best validation model: TF-IDF + Logistic Regression
Test accuracy: 0.8710

Test classification report:
              precision    recall  f1-score   support

    negative       0.89      0.85      0.87      1000
    positive       0.85      0.89      0.87      1000

    accuracy                           0.87      2000
   macro avg       0.87      0.87      0.87      2000
weighted avg       0.87      0.87      0.87      2000

## Notes

The best validation result among the classical baselines is obtained by TF-IDF with Logistic Regression. TF-IDF with Linear SVC is the second strongest model in this comparison, reaching 0.858 validation accuracy. Logistic Regression will be used as the main classical reference model for later transformer-based experiments.